# Generated by Django 6.0 on 2026-01-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
